---
- name: Create /etc/gunicorn
  file: 
    name: /etc/gunicorn 
    state: directory

- name: Copy the gunicorn config file
  template: 
    src: gunicorn.py.j2 
    dest: "/etc/gunicorn/{{ gunicorn_app_name }}.py"

- name: Install gunicorn
  pip: 
    name: gunicorn 
    virtualenv: "{{ virtualenv_path }}"
    version: "{{ gunicorn_version }}"